### ISSUE TITLE
cycles_visibility error in Blender 3.2

### ISSUE THREAD

**Issue by mtnknk** [gregzaal/Gaffer#151]
Hi, I got the following error in Blender 3.2. I am not familiar with Blender's API, but the specification may have changed. For now, I commented out the relevant lines.

```
Python: Traceback (most recent call last):
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Gaffer\ui.py", line 897, in draw
    draw_cycles_eevee_UI(context, layout, lights)
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Gaffer\ui.py", line 705, in draw_cycles_eevee_UI
    draw_more_options_cycles(
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Gaffer\ui.py", line 279, in draw_more_options_cycles
    row.prop(light.cycles_visibility, "diffuse", text="Diff", toggle=True)
AttributeError: 'Object' object has no attribute 'cycles_visibility'
```

https://github.com/gregzaal/Gaffer/blob/d1834374b10940f2ffd3aa16426faa7e11600b92/ui.py#L279-L280

**Comment by gregzaal** [comment]
Thanks for the report!
