### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by gregzaal** [gregzaal/Gaffer#54]
`Color management: display "sRGB" used by scene not found, setting to default ("sRGB / BT.709").
Color management: scene view "Default" not found, setting default "sRGB EOTF".
Color management: sequencer colorspace "sRGB" not found, will use default instead.
Read new prefs: C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.78\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.78\python
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\modules\addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\Gaffer-master\__init__.py", line 40, in <module>
    from . import constants, functions, operators, ui, addon_updater, addon_updater_ops
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\Gaffer-master\functions.py", line 1195, in <module>
    hdri_haven_list = get_hdri_haven_list()
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\Gaffer-master\functions.py", line 1191, in get_hdri_haven_list
    hdrihaven_hdris = html.split('### list after this! ###')[1].split('<br>')[:-1]
IndexError: list index out of range
addon_utils.disable: Gaffer-master not disabled.
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\modules\addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\Gaffer-master\__init__.py", line 40, in <module>
    from . import constants, functions, operators, ui, addon_updater, addon_updater_ops
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\Gaffer-master\functions.py", line 1195, in <module>
    hdri_haven_list = get_hdri_haven_list()
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\Gaffer-master\functions.py", line 1191, in get_hdri_haven_list
    hdrihaven_hdris = html.split('### list after this! ###')[1].split('<br>')[:-1]
IndexError: list index out of range`

**Comment by gregzaal** [comment]
Older version broke after updates to server-generated hdri haven list. Newer version (after 24e64ac2) should work.
