### ISSUE TITLE
Error when refreshing HDRI list

### ISSUE THREAD

**Issue by gregzaal** [gregzaal/Gaffer#97]
```
C:\Program Files\Blender\2.8>blender.exe
Read prefs: C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\Program Files\Blender\2.8\2.80\python
multiple addons with the same name:
  'C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\render_auto_save.py'
  'C:\Program Files\Blender\2.8\2.80\scripts\addons_contrib\render_auto_save.py'
addon_utils.disable: Gaffer-master not loaded
Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Gaffer-blender28\operators.py", line 1091, in execute
    detect_hdris(self, context)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Gaffer-blender28\functions.py", line 629, in detect_hdris
    if context.scene.gaf_props['hdri'] >= len(hdri_list):
KeyError: 'bpy_struct[key]: key "hdri" not found'
```

**Comment by gregzaal** [comment]
Fixed in ea8fd8d0ab67815f6ae7b91dae4914acdfce9ed9
